config/routes.rb
JdSite::Application.routes.draw do

  resources :contacts, only: [:new, :create]
  root to: 'contacts#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base 
  has_no_table

  column :name, :string 
  column :email, :string 
  column :content, :string
  validates_presence_of :name, :email, :content
  validates_format_of :email,
    :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i 
  validates_length_of :content, :maximum => 500

  def update_spreadsheet
  connect_to_drive = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
  contact_info = connect_to_drive.spreadsheet_by_title('JDExcel Contacts')
  if contact_info.nil?
    contact_info = connect_to_drive.create_spreadsheet('Contact Information') 
  end
  excel_sheet = contact_info.worksheets[0] 
  last_row = 1 + excel_sheet.num_rows 
  excel_sheet[last_row, 1] = Time.new 
  excel_sheet[last_row, 2] = self.name 
  excel_sheet[last_row, 3] = self.email 
  excel_sheet[last_row, 4] = self.content 
  excel_sheet.save
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(secure_params) 
    if @contact.valid?
      @contact.update_spreadsheet
      flash[:notice] = "Message sent from #{@contact.name}." 
      redirect_to root_path
    else
      render :new
    end 
  end
  

  private
    def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %> 
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for @contact do |form| %> 
  <%= form.error_notification %>
  <%= form.input :name, autofocus: true %> 
  <%= form.input :email %>
  <%= form.input :content, label: "How can we help?", as: :text %>
  <%= form.button :submit, 'Submit', class: 'submit' %> <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li> 
<li><%= link_to 'Contact', new_contact_path %></li>
<li><%= link_to 'Pricing', page_path('pricing') %></li>
<li><%= link_to 'FAQ', page_path('faq') %></li>
<li><%= link_to 'Privacy Policy', page_path('terms-conditions') %></li>
<li><%= link_to 'Admissions Consulting', page_path('law_school_admissions') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jd Site" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jd Site" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h1>Header</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id feugiat neque, eget lacinia leo. Integer in sagittis tellus. Etiam at magna felis. Etiam felis purus, tristique vel enim a, ultrices auctor lacus. Fusce elementum euismod felis, eget pellentesque nibh tempus a. Sed venenatis risus vitae nibh ullamcorper, nec auctor enim suscipit. Vestibulum nec elementum risus. Nulla tincidunt lobortis justo quis gravida. Nulla rutrum orci at ultrices tempus. Sed magna risus, viverra et augue sit amet, adipiscing ornare nisi. Phasellus fermentum porta accumsan. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin mattis nunc id ligula fermentum, eget sollicitudin purus ullamcorper. Donec luctus, turpis id semper dictum, dolor risus adipiscing leo, mollis auctor dolor nisl eget tortor. Aliquam eget nibh et mauris convallis eleifend. Nulla eu arcu quis dolor pellentesque rutrum.

Pellentesque ut diam felis. Nullam a massa diam. Curabitur quis varius mi. Vestibulum nec ante nisi. Donec eu dui sem. Morbi consequat pharetra interdum. Aenean eu pulvinar felis. Cras eleifend luctus ipsum, et fringilla dui volutpat sit amet. Etiam eget augue sed mauris posuere facilisis vel et lacus. Phasellus adipiscing sodales ligula. Suspendisse in placerat magna. Maecenas leo mauris, auctor a justo vitae, aliquet pellentesque risus. Sed rhoncus urna a molestie rhoncus.

Praesent pretium turpis arcu, eu varius augue ullamcorper at. Nullam mattis quam sit amet molestie vulputate. Suspendisse vel urna neque. Sed et orci sed dolor tincidunt scelerisque ut eget orci. Nulla sed viverra purus. Pellentesque sed bibendum mi. Maecenas elementum dictum risus, molestie euismod lacus bibendum vel. Vivamus eu aliquam augue.

Fusce scelerisque, sapien lacinia vestibulum malesuada, augue lectus aliquam arcu, vel tempor erat enim vel quam. Aenean luctus sodales urna ac mattis. Praesent et blandit augue. Praesent eu tellus non diam sagittis tempor. Nullam vitae nibh semper, pellentesque massa sit amet, condimentum nisi. Nunc at consequat purus. Ut magna tellus, luctus ac neque eget, tincidunt malesuada elit. Maecenas sed ante vitae dolor pharetra interdum nec non augue. Aenean lacus nisi, consectetur non nisi eu, feugiat placerat diam. Quisque in lectus faucibus metus laoreet dignissim id nec enim. Nulla pellentesque convallis orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In dignissim velit in aliquet tincidunt. Nam ullamcorper, tellus vel tempus molestie, tortor lorem varius leo, at luctus est purus sit amet purus. In ac sapien scelerisque elit pulvinar tempus non eu arcu.

Duis gravida accumsan molestie. Duis placerat ligula et molestie congue. Pellentesque non faucibus lectus, ac bibendum nunc. Donec molestie, magna porttitor porttitor aliquet, mauris ipsum eleifend purus, sed dapibus odio nulla a lectus. Phasellus ut erat id sem dictum luctus. Ut lobortis, ligula quis blandit pharetra, nisi metus iaculis nunc, ac porttitor turpis felis sit amet nulla. Aliquam quis turpis tristique, tristique odio rutrum, sodales est. Nam semper mollis mi, id suscipit enim. Vestibulum blandit, elit venenatis molestie congue, dui leo commodo elit, nec venenatis ante ante ut lectus. Suspendisse consectetur sagittis aliquet. Nulla quis sapien vel metus adipiscing pharetra eu sed metus.</p>

app/views/pages/contact.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>

app/views/pages/faq.html.erb
<% content_for :title do %>FAQ<% end %>
<h3>FAQ</h3>

app/views/pages/law_school_admissions_consulting.html.erb
<% content_for :title do %>Admissions Consulting<% end %>
<h3>Admissions Consulting</h3>

app/views/pages/pricing.html.erb
<% content_for :title do %>Pricing<% end %>
<h3>Pricing</h3>

app/views/pages/terms-conditions.html.erb
<% content_for :title do %>Privacy Policy<% end %>
<h3>Privacy Policy</h3>